### ISSUE TITLE
Enable automatic loaders for external components

### ISSUE THREAD

**Issue by mandryllo** [tailor-cms/tce-template#15]
For example `lxp-ui` published as github package

**Comment by underscope** [comment]
Closing this as the actual request is for the runtime to expose/inject components which are private packages and which would need to be supplied and configured somehow (not installing components to any of the frontend packages (display / edit). Forking / customising the runtime is the way to go here at the moment.

**Comment by tueda-hvd** [comment]
Just to be clear, "fork" here means

* forking both `tailor-cms/xt` and `tailor-cms/tce-template`
* publishing the fork of `xt` to a separate package, and
* updating the dependencies in the fork of `tce-template`

correct?

If so, this seems like a lot of overhead and upstream management. Could you explain why runtime hooks (e.g. modifying/changing the Vuetify config, or adjusting the plugins added to the Vue app) are not a viable option?

**Comment by underscope** [comment]
Might be easier to discuss on our next sync 😉 Please add it to the list
