### ISSUE TITLE
Add transient state to the context

### ISSUE THREAD

**Issue by dbettini** [tailor-cms/tce-template#18]
## Problem
Currently, there is no way to handle request scoped state passing. This would be useful for notifications, validation, and other cases which are not stored on the server permanently.

## Possible solution
A `transientState` could be passed through the `onUserInteraction` output, to the immediate `beforeDisplay` that follows, which would enable the aforementioned use cases. This is similar to how `updateDisplayState` is passed and applied.

More context [here](https://hlxp.atlassian.net/wiki/spaces/ML/pages/280920083/CDA+Content+Element+Interface).

**Comment by underscope** [comment]
Implemented as suggested. You can pass back `transientState` from the `onUserInteraction` hook to the `beforeDisplay` hook. For more details see the [docs](https://tailor-cms.github.io/xt/server-package.html#onuserinteraction-hook). To migrate simply bump tce-boot to 0.2.1.
